name: 'CI'

on:
  push:
    branches:
    - main
    - features/**
    - feature/**
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
    - name: Cache ~/.nuget/packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/*.targets') }}
    - run: dotnet --info
    
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest')
      run: |
        dotnet nuget push .\nuget\*.nupkg -s https://www.myget.org/F/dangl-internal/api/v2/package -k ${{ secrets.MYGET_PUSH_KEY }}
